### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zetnet** [eMBee/vimeo-download#13]
root@5c7bcadea91f:/usr/src/app# python vimeo-download.py --url "https://137skyfiregce-vimeo.akamaized.net/exp=1537799112~acl=%2F200853336%2F%2A~hmac=50b46c653542bd75b87f6da52d9d549be79267263faafc47e07fe2baa8560947/200853336/sep/video/678908315,678908317,678908316,678908303,678908301/master.json?base64_init=1" --output iiiiim.mp4
Creating /usr/src/app/temp...
Creating /usr/src/app/output...
Output filename set to: /usr/src/app/output/iiiiim.mp4.mp4
Traceback (most recent call last):
  File "vimeo-download.py", line 166, in <module>
    content = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@5c7bcadea91f:/usr/src/app#

**Comment by thidiniz** [comment]
same here:

C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32>python vimeo-download
.py --url "https://49skyfiregce-vimeo.akamaized.net/exp=1539635728~acl=F26544964
8FA~hmac=c0d5a0e1dba37876f92c296b43de83d7b6d5350ad72208ce5318df2695ef0caf/265449
648/sep/video/981516865,981516874,981516871,981516866/master.json?base64_init=1"
 --output C:\Downloads\Teste
Output filename set to: C:\Downloads\Teste.mp4
Traceback (most recent call last):
  File "vimeo-download.py", line 166, in <module>
    content = resp.json()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\requests\models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\json\__in
it__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\json\deco
der.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\lib\json\deco
der.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by maxxi165** [comment]
Trying to open this url in browser it says "Access Denied"
