### ISSUE TITLE
Audio segments

### ISSUE THREAD

**Issue by armincpath** [eMBee/vimeo-download#7]
Hey everyone,

I was trying to download the following master:
https://122skyfiregce-vimeo.akamaized.net/exp=1513969793~acl=%2F217512921%2F%2A~hmac=d27f90c9b8922f64c901a4bd33b8b7f778e3b2621e0a90baad3318669cf72d4f/217512921/video/753333160,753333156,753333155,753333151/master.json?base64_init=1

The video segments were downloaded successfully, but I got an error in the audio segments part.

`Traceback (most recent call last):
  File "vimeo-download.py", line 170, in <module>
    download_audio(base_url, content)
  File "vimeo-download.py", line 89, in download_audio
    audio = content['audio'][0]
TypeError: 'NoneType' object has no attribute '__getitem__'`

Other thing, did you notice that if you remove the "base64_" from the url, it returns the first file name without base64 encriptation? Like:
https://122skyfiregce-vimeo.akamaized.net/exp=1513969793~acl=%2F217512921%2F%2A~hmac=d27f90c9b8922f64c901a4bd33b8b7f778e3b2621e0a90baad3318669cf72d4f/217512921/video/753333160,753333156,753333155,753333151/master.json?**init=1**

Thank you :)

ps: If I knew how to debug step-by-step python, I would have figure it out and push it here.

**Comment by maxxi165** [comment]
Trying to open this url in browser it says "Access Denied"
